apiVersion: v1
kind: Service
metadata:
  name: node-proxy
#  annotations:
#     dev.okteto.com/auto-ingress: "true"
#     dev.okteto.com/generate-host: "true"
  
spec:
  selector:
    app: node-web-server
  ports:
    - port: 80
      targetPort: 3000
#   type: NodePort
  type: LoadBalancer
#  type: ClusterIP
