apiVersion: v1
kind: Service
metadata:
  name: cache-service
  annotations:
     dev.okteto.com/auto-ingress: "true"
     dev.okteto.com/generate-host: "true"
  
spec:
  selector:
    app: cache
  ports:
    - port: 6379
      targetPort: 6379
#   type: NodePort
#  type: LoadBalancer
  type: ClusterIP
