apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: cache
  type: ClusterIP
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache
spec:
  selector:
    matchLabels:
      app: redis 
  serviceName: "redis"
  replicas: 
  template:
    metadata:
      labels:
        app: redis 
    spec:
      volumes:
       - name: vol
         hostPath:
           path: /opt/data
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        volumeMounts:
          - name: vol
            mountPath: /data/
        lifecycle:
           postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 10; cat /data/dat.txt | redis-cli --pipe"]
        ports:
        - containerPort: 6379
          name: cache


