apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-web-server
  name: node-proxy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-web-server
  type: LoadBalancer
status:
  loadBalancer: {}
