name: Docker Hub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
           DOCKER_USER: ${{ secrets.DOCKER_USER }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
             env
      - name: docker build
        run: |
            docker build -t ${{ secrets.DOCKER_USER }}/rprod:latest .
#       - name: docker psuh
#         run: |
#             docker push $DOCKER_USER/rprod:latest 
