name: Docker Hub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        run: docker login sprx7767/rprod -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Docker Build
        run: docker build -t sprx7767/rprod .
      
      - name: Docker push
        run: docker push sprx7767/rprod
