name: Docker Hub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
      - name: Docker Login
        working-directory: ${{env.working-directory}}
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
      - name: Docker Build
        working-directory: ${{env.working-directory}}
        run: docker build -t sprx7767/rprod:latest .
      
      - name: Docker push
        working-directory: ${{env.working-directory}}
        run: docker push sprx7767/rprod
