name: Docker Hub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        REPO: rprod
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build
      run: |
        docker build -t $DOCKER_USER/$REPO:latest .
    - name: docker push
      run: |
        docker push $DOCKER_USER/$REPO:latest
        
            
