name: Docker Hub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login       
        run: |
             export DOCKER_USER=${{ secrets.DOCKER_USER }} && DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
      - name: envi
        run: |
         echo $DOCKER_USER
#       - name: docker build
#         run: |
#             docker build -t $(echo $DOCKER_USER)/rprod:latest .
#       - name: docker psuh
#         run: |
#             docker push $DOCKER_USER/rprod:latest 
