name: Docker Hub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      - name: Build and push Docker images
      #  uses: docker/build-push-action@v1.1.0
        run: ls -la
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           repository: ${{ secrets.DOCKER_USERNAME }}/rprod
#           tags: latest
